/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AutomationResolverInterface extends Interface {
    getFunction(nameOrSignature: "addPriceMarket" | "checkUpkeep" | "getMarketCount" | "getMarketIdAt" | "oracleConsumer" | "owner" | "performUpkeep" | "predictionMarket" | "priceMarkets" | "registry" | "removePriceMarket" | "setOracleConsumer" | "setRegistry"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MarketResolvedByAutomation" | "OracleConsumerSet" | "PriceMarketAdded" | "RegistrySet"): EventFragment;

    encodeFunctionData(functionFragment: 'addPriceMarket', values: [BigNumberish, AddressLike, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'checkUpkeep', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getMarketCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getMarketIdAt', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'oracleConsumer', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'performUpkeep', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'predictionMarket', values?: undefined): string;
encodeFunctionData(functionFragment: 'priceMarkets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registry', values?: undefined): string;
encodeFunctionData(functionFragment: 'removePriceMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setOracleConsumer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setRegistry', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'addPriceMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkUpkeep', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMarketCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMarketIdAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracleConsumer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'performUpkeep', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'predictionMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'priceMarkets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removePriceMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOracleConsumer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRegistry', data: BytesLike): Result;
  }

  
    export namespace MarketResolvedByAutomationEvent {
      export type InputTuple = [marketId: BigNumberish, price: BigNumberish, outcome: BigNumberish];
      export type OutputTuple = [marketId: bigint, price: bigint, outcome: bigint];
      export interface OutputObject {marketId: bigint, price: bigint, outcome: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OracleConsumerSetEvent {
      export type InputTuple = [oracleConsumer: AddressLike];
      export type OutputTuple = [oracleConsumer: string];
      export interface OutputObject {oracleConsumer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PriceMarketAddedEvent {
      export type InputTuple = [marketId: BigNumberish, feed: AddressLike, threshold: BigNumberish, greaterThan: boolean];
      export type OutputTuple = [marketId: bigint, feed: string, threshold: bigint, greaterThan: boolean];
      export interface OutputObject {marketId: bigint, feed: string, threshold: bigint, greaterThan: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RegistrySetEvent {
      export type InputTuple = [registry: AddressLike];
      export type OutputTuple = [registry: string];
      export interface OutputObject {registry: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AutomationResolver extends BaseContract {
    
    connect(runner?: ContractRunner | null): AutomationResolver;
    waitForDeployment(): Promise<this>;

    interface: AutomationResolverInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addPriceMarket: TypedContractMethod<
      [marketId: BigNumberish, feed: AddressLike, threshold: BigNumberish, greaterThan: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    checkUpkeep: TypedContractMethod<
      [arg0: BytesLike, ],
      [[boolean, string] & {upkeepNeeded: boolean, performData: string }],
      'view'
    >
    

    
    getMarketCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getMarketIdAt: TypedContractMethod<
      [index: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    oracleConsumer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    performUpkeep: TypedContractMethod<
      [performData: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    predictionMarket: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    priceMarkets: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, boolean] & {feed: string, threshold: bigint, greaterThan: boolean }],
      'view'
    >
    

    
    registry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    removePriceMarket: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setOracleConsumer: TypedContractMethod<
      [newOracleConsumer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setRegistry: TypedContractMethod<
      [newRegistry: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addPriceMarket'): TypedContractMethod<
      [marketId: BigNumberish, feed: AddressLike, threshold: BigNumberish, greaterThan: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'checkUpkeep'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[boolean, string] & {upkeepNeeded: boolean, performData: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getMarketCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMarketIdAt'): TypedContractMethod<
      [index: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'oracleConsumer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'performUpkeep'): TypedContractMethod<
      [performData: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'predictionMarket'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'priceMarkets'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, boolean] & {feed: string, threshold: bigint, greaterThan: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'registry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'removePriceMarket'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setOracleConsumer'): TypedContractMethod<
      [newOracleConsumer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRegistry'): TypedContractMethod<
      [newRegistry: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'MarketResolvedByAutomation'): TypedContractEvent<MarketResolvedByAutomationEvent.InputTuple, MarketResolvedByAutomationEvent.OutputTuple, MarketResolvedByAutomationEvent.OutputObject>;
getEvent(key: 'OracleConsumerSet'): TypedContractEvent<OracleConsumerSetEvent.InputTuple, OracleConsumerSetEvent.OutputTuple, OracleConsumerSetEvent.OutputObject>;
getEvent(key: 'PriceMarketAdded'): TypedContractEvent<PriceMarketAddedEvent.InputTuple, PriceMarketAddedEvent.OutputTuple, PriceMarketAddedEvent.OutputObject>;
getEvent(key: 'RegistrySet'): TypedContractEvent<RegistrySetEvent.InputTuple, RegistrySetEvent.OutputTuple, RegistrySetEvent.OutputObject>;

    filters: {
      
      'MarketResolvedByAutomation(uint256,int256,uint8)': TypedContractEvent<MarketResolvedByAutomationEvent.InputTuple, MarketResolvedByAutomationEvent.OutputTuple, MarketResolvedByAutomationEvent.OutputObject>;
      MarketResolvedByAutomation: TypedContractEvent<MarketResolvedByAutomationEvent.InputTuple, MarketResolvedByAutomationEvent.OutputTuple, MarketResolvedByAutomationEvent.OutputObject>;
    

      'OracleConsumerSet(address)': TypedContractEvent<OracleConsumerSetEvent.InputTuple, OracleConsumerSetEvent.OutputTuple, OracleConsumerSetEvent.OutputObject>;
      OracleConsumerSet: TypedContractEvent<OracleConsumerSetEvent.InputTuple, OracleConsumerSetEvent.OutputTuple, OracleConsumerSetEvent.OutputObject>;
    

      'PriceMarketAdded(uint256,address,int256,bool)': TypedContractEvent<PriceMarketAddedEvent.InputTuple, PriceMarketAddedEvent.OutputTuple, PriceMarketAddedEvent.OutputObject>;
      PriceMarketAdded: TypedContractEvent<PriceMarketAddedEvent.InputTuple, PriceMarketAddedEvent.OutputTuple, PriceMarketAddedEvent.OutputObject>;
    

      'RegistrySet(address)': TypedContractEvent<RegistrySetEvent.InputTuple, RegistrySetEvent.OutputTuple, RegistrySetEvent.OutputObject>;
      RegistrySet: TypedContractEvent<RegistrySetEvent.InputTuple, RegistrySetEvent.OutputTuple, RegistrySetEvent.OutputObject>;
    
    };
  }