/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ConditionalMarket {
      
    export type ConditionStruct = {marketContract: AddressLike, marketId: BigNumberish, expectedOutcome: BigNumberish}

    export type ConditionStructOutput = [marketContract: string, marketId: bigint, expectedOutcome: bigint] & {marketContract: string, marketId: bigint, expectedOutcome: bigint }
  
    }

  export interface ConditionalMarketInterface extends Interface {
    getFunction(nameOrSignature: "claimPayout" | "createConditionalMarket" | "getMarket" | "lockMarket" | "owner" | "placeBet" | "resolveMarket" | "resolver" | "setResolver"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BetPlaced" | "ConditionAdded" | "ConditionalMarketCreated" | "MarketLocked" | "MarketResolved" | "PayoutClaimed"): EventFragment;

    encodeFunctionData(functionFragment: 'claimPayout', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createConditionalMarket', values: [string, BigNumberish, BigNumberish, ConditionalMarket.ConditionStruct[]]): string;
encodeFunctionData(functionFragment: 'getMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'lockMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'placeBet', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolveMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolver', values?: undefined): string;
encodeFunctionData(functionFragment: 'setResolver', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'claimPayout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createConditionalMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeBet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolver', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setResolver', data: BytesLike): Result;
  }

  
    export namespace BetPlacedEvent {
      export type InputTuple = [marketId: BigNumberish, user: AddressLike, outcome: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [marketId: bigint, user: string, outcome: bigint, amount: bigint];
      export interface OutputObject {marketId: bigint, user: string, outcome: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ConditionAddedEvent {
      export type InputTuple = [marketId: BigNumberish, marketContract: AddressLike, conditionMarketId: BigNumberish];
      export type OutputTuple = [marketId: bigint, marketContract: string, conditionMarketId: bigint];
      export interface OutputObject {marketId: bigint, marketContract: string, conditionMarketId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ConditionalMarketCreatedEvent {
      export type InputTuple = [marketId: BigNumberish, creator: AddressLike, question: string];
      export type OutputTuple = [marketId: bigint, creator: string, question: string];
      export interface OutputObject {marketId: bigint, creator: string, question: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketLockedEvent {
      export type InputTuple = [marketId: BigNumberish];
      export type OutputTuple = [marketId: bigint];
      export interface OutputObject {marketId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketResolvedEvent {
      export type InputTuple = [marketId: BigNumberish, outcome: BigNumberish];
      export type OutputTuple = [marketId: bigint, outcome: bigint];
      export interface OutputObject {marketId: bigint, outcome: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PayoutClaimedEvent {
      export type InputTuple = [marketId: BigNumberish, user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [marketId: bigint, user: string, amount: bigint];
      export interface OutputObject {marketId: bigint, user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ConditionalMarket extends BaseContract {
    
    connect(runner?: ContractRunner | null): ConditionalMarket;
    waitForDeployment(): Promise<this>;

    interface: ConditionalMarketInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    claimPayout: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createConditionalMarket: TypedContractMethod<
      [question: string, closeTime: BigNumberish, resolveTime: BigNumberish, conditions: ConditionalMarket.ConditionStruct[], ],
      [bigint],
      'nonpayable'
    >
    

    
    getMarket: TypedContractMethod<
      [marketId: BigNumberish, ],
      [[string, bigint, bigint, bigint] & {question: string, status: bigint, outcome: bigint, conditionsCount: bigint }],
      'view'
    >
    

    
    lockMarket: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    placeBet: TypedContractMethod<
      [marketId: BigNumberish, outcome: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    resolveMarket: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolver: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setResolver: TypedContractMethod<
      [newResolver: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'claimPayout'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createConditionalMarket'): TypedContractMethod<
      [question: string, closeTime: BigNumberish, resolveTime: BigNumberish, conditions: ConditionalMarket.ConditionStruct[], ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getMarket'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [[string, bigint, bigint, bigint] & {question: string, status: bigint, outcome: bigint, conditionsCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'lockMarket'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'placeBet'): TypedContractMethod<
      [marketId: BigNumberish, outcome: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'resolveMarket'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolver'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setResolver'): TypedContractMethod<
      [newResolver: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BetPlaced'): TypedContractEvent<BetPlacedEvent.InputTuple, BetPlacedEvent.OutputTuple, BetPlacedEvent.OutputObject>;
getEvent(key: 'ConditionAdded'): TypedContractEvent<ConditionAddedEvent.InputTuple, ConditionAddedEvent.OutputTuple, ConditionAddedEvent.OutputObject>;
getEvent(key: 'ConditionalMarketCreated'): TypedContractEvent<ConditionalMarketCreatedEvent.InputTuple, ConditionalMarketCreatedEvent.OutputTuple, ConditionalMarketCreatedEvent.OutputObject>;
getEvent(key: 'MarketLocked'): TypedContractEvent<MarketLockedEvent.InputTuple, MarketLockedEvent.OutputTuple, MarketLockedEvent.OutputObject>;
getEvent(key: 'MarketResolved'): TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
getEvent(key: 'PayoutClaimed'): TypedContractEvent<PayoutClaimedEvent.InputTuple, PayoutClaimedEvent.OutputTuple, PayoutClaimedEvent.OutputObject>;

    filters: {
      
      'BetPlaced(uint256,address,uint8,uint256)': TypedContractEvent<BetPlacedEvent.InputTuple, BetPlacedEvent.OutputTuple, BetPlacedEvent.OutputObject>;
      BetPlaced: TypedContractEvent<BetPlacedEvent.InputTuple, BetPlacedEvent.OutputTuple, BetPlacedEvent.OutputObject>;
    

      'ConditionAdded(uint256,address,uint256)': TypedContractEvent<ConditionAddedEvent.InputTuple, ConditionAddedEvent.OutputTuple, ConditionAddedEvent.OutputObject>;
      ConditionAdded: TypedContractEvent<ConditionAddedEvent.InputTuple, ConditionAddedEvent.OutputTuple, ConditionAddedEvent.OutputObject>;
    

      'ConditionalMarketCreated(uint256,address,string)': TypedContractEvent<ConditionalMarketCreatedEvent.InputTuple, ConditionalMarketCreatedEvent.OutputTuple, ConditionalMarketCreatedEvent.OutputObject>;
      ConditionalMarketCreated: TypedContractEvent<ConditionalMarketCreatedEvent.InputTuple, ConditionalMarketCreatedEvent.OutputTuple, ConditionalMarketCreatedEvent.OutputObject>;
    

      'MarketLocked(uint256)': TypedContractEvent<MarketLockedEvent.InputTuple, MarketLockedEvent.OutputTuple, MarketLockedEvent.OutputObject>;
      MarketLocked: TypedContractEvent<MarketLockedEvent.InputTuple, MarketLockedEvent.OutputTuple, MarketLockedEvent.OutputObject>;
    

      'MarketResolved(uint256,uint8)': TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
      MarketResolved: TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
    

      'PayoutClaimed(uint256,address,uint256)': TypedContractEvent<PayoutClaimedEvent.InputTuple, PayoutClaimedEvent.OutputTuple, PayoutClaimedEvent.OutputObject>;
      PayoutClaimed: TypedContractEvent<PayoutClaimedEvent.InputTuple, PayoutClaimedEvent.OutputTuple, PayoutClaimedEvent.OutputObject>;
    
    };
  }