/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CREWorkflowInterface extends Interface {
    getFunction(nameOrSignature: "authorizedAutomation" | "oracle" | "owner" | "predictionMarket" | "resolveFromOracle" | "setAuthorizedAutomation" | "setOracle"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'authorizedAutomation', values?: undefined): string;
encodeFunctionData(functionFragment: 'oracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'predictionMarket', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveFromOracle', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setAuthorizedAutomation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setOracle', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'authorizedAutomation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'predictionMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveFromOracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAuthorizedAutomation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOracle', data: BytesLike): Result;
  }

  

  export interface CREWorkflow extends BaseContract {
    
    connect(runner?: ContractRunner | null): CREWorkflow;
    waitForDeployment(): Promise<this>;

    interface: CREWorkflowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    authorizedAutomation: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    oracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    predictionMarket: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    resolveFromOracle: TypedContractMethod<
      [marketId: BigNumberish, rawOutcome: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setAuthorizedAutomation: TypedContractMethod<
      [newAutomation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setOracle: TypedContractMethod<
      [newOracle: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'authorizedAutomation'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'oracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'predictionMarket'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'resolveFromOracle'): TypedContractMethod<
      [marketId: BigNumberish, rawOutcome: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAuthorizedAutomation'): TypedContractMethod<
      [newAutomation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setOracle'): TypedContractMethod<
      [newOracle: AddressLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }