/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'AutomationResolver', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AutomationResolver__factory>
getContractFactory(name: 'CREWorkflow', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.CREWorkflow__factory>
getContractFactory(name: 'ConditionalMarket', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ConditionalMarket__factory>
getContractFactory(name: 'OracleConsumer', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.OracleConsumer__factory>
getContractFactory(name: 'PredictionMarket', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PredictionMarket__factory>
getContractFactory(name: 'PredictionMarketFunctionsConsumer', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PredictionMarketFunctionsConsumer__factory>
getContractFactory(name: 'PrivatePredictionMarket', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PrivatePredictionMarket__factory>
getContractFactory(name: 'ReputationSystem', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ReputationSystem__factory>
getContractFactory(name: 'TokenizedMarket', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TokenizedMarket__factory>
getContractFactory(name: 'IPredictionMarket', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IPredictionMarket__factory>
getContractFactory(name: 'IReputationSystem', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IReputationSystem__factory>

  getContractAt(name: 'AutomationResolver', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AutomationResolver>
getContractAt(name: 'CREWorkflow', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.CREWorkflow>
getContractAt(name: 'ConditionalMarket', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ConditionalMarket>
getContractAt(name: 'OracleConsumer', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.OracleConsumer>
getContractAt(name: 'PredictionMarket', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PredictionMarket>
getContractAt(name: 'PredictionMarketFunctionsConsumer', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PredictionMarketFunctionsConsumer>
getContractAt(name: 'PrivatePredictionMarket', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PrivatePredictionMarket>
getContractAt(name: 'ReputationSystem', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ReputationSystem>
getContractAt(name: 'TokenizedMarket', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TokenizedMarket>
getContractAt(name: 'IPredictionMarket', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IPredictionMarket>
getContractAt(name: 'IReputationSystem', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IReputationSystem>

  deployContract(name: 'AutomationResolver', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AutomationResolver>
deployContract(name: 'CREWorkflow', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CREWorkflow>
deployContract(name: 'ConditionalMarket', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ConditionalMarket>
deployContract(name: 'OracleConsumer', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OracleConsumer>
deployContract(name: 'PredictionMarket', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PredictionMarket>
deployContract(name: 'PredictionMarketFunctionsConsumer', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PredictionMarketFunctionsConsumer>
deployContract(name: 'PrivatePredictionMarket', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PrivatePredictionMarket>
deployContract(name: 'ReputationSystem', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ReputationSystem>
deployContract(name: 'TokenizedMarket', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenizedMarket>
deployContract(name: 'IPredictionMarket', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPredictionMarket>
deployContract(name: 'IReputationSystem', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReputationSystem>

  deployContract(name: 'AutomationResolver', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AutomationResolver>
deployContract(name: 'CREWorkflow', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.CREWorkflow>
deployContract(name: 'ConditionalMarket', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ConditionalMarket>
deployContract(name: 'OracleConsumer', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.OracleConsumer>
deployContract(name: 'PredictionMarket', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PredictionMarket>
deployContract(name: 'PredictionMarketFunctionsConsumer', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PredictionMarketFunctionsConsumer>
deployContract(name: 'PrivatePredictionMarket', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PrivatePredictionMarket>
deployContract(name: 'ReputationSystem', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ReputationSystem>
deployContract(name: 'TokenizedMarket', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TokenizedMarket>
deployContract(name: 'IPredictionMarket', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPredictionMarket>
deployContract(name: 'IReputationSystem', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IReputationSystem>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  