/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface OracleConsumerInterface extends Interface {
    getFunction(nameOrSignature: "authorizedAutomation" | "authorizedCallback" | "creWorkflow" | "oracleCallback" | "owner" | "setAuthorizedAutomation" | "setAuthorizedCallback" | "setCreWorkflow"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'authorizedAutomation', values?: undefined): string;
encodeFunctionData(functionFragment: 'authorizedCallback', values?: undefined): string;
encodeFunctionData(functionFragment: 'creWorkflow', values?: undefined): string;
encodeFunctionData(functionFragment: 'oracleCallback', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAuthorizedAutomation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setAuthorizedCallback', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setCreWorkflow', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'authorizedAutomation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedCallback', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creWorkflow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracleCallback', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAuthorizedAutomation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAuthorizedCallback', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCreWorkflow', data: BytesLike): Result;
  }

  

  export interface OracleConsumer extends BaseContract {
    
    connect(runner?: ContractRunner | null): OracleConsumer;
    waitForDeployment(): Promise<this>;

    interface: OracleConsumerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    authorizedAutomation: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    authorizedCallback: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    creWorkflow: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    oracleCallback: TypedContractMethod<
      [marketId: BigNumberish, rawOutcome: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setAuthorizedAutomation: TypedContractMethod<
      [newAutomation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setAuthorizedCallback: TypedContractMethod<
      [newCallback: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setCreWorkflow: TypedContractMethod<
      [newCreWorkflow: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'authorizedAutomation'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'authorizedCallback'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'creWorkflow'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'oracleCallback'): TypedContractMethod<
      [marketId: BigNumberish, rawOutcome: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setAuthorizedAutomation'): TypedContractMethod<
      [newAutomation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAuthorizedCallback'): TypedContractMethod<
      [newCallback: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCreWorkflow'): TypedContractMethod<
      [newCreWorkflow: AddressLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }