/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace IPredictionMarket {
      
    export type MarketViewStruct = {id: BigNumberish, question: string, closeTime: BigNumberish, resolveTime: BigNumberish, status: BigNumberish, outcome: BigNumberish, totalYesStake: BigNumberish, totalNoStake: BigNumberish}

    export type MarketViewStructOutput = [id: bigint, question: string, closeTime: bigint, resolveTime: bigint, status: bigint, outcome: bigint, totalYesStake: bigint, totalNoStake: bigint] & {id: bigint, question: string, closeTime: bigint, resolveTime: bigint, status: bigint, outcome: bigint, totalYesStake: bigint, totalNoStake: bigint }
  
    }

  export interface PredictionMarketInterface extends Interface {
    getFunction(nameOrSignature: "claimPayout" | "createMarket" | "getMarket" | "getUserStake" | "lockMarket" | "owner" | "placeBet" | "reputationSystem" | "resolveMarket" | "resolver" | "setReputationSystem" | "setResolver"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BetPlaced" | "MarketCreated" | "MarketLocked" | "MarketResolved" | "PayoutClaimed"): EventFragment;

    encodeFunctionData(functionFragment: 'claimPayout', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createMarket', values: [string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getUserStake', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'lockMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'placeBet', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'reputationSystem', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveMarket', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolver', values?: undefined): string;
encodeFunctionData(functionFragment: 'setReputationSystem', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setResolver', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'claimPayout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserStake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeBet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputationSystem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolver', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setReputationSystem', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setResolver', data: BytesLike): Result;
  }

  
    export namespace BetPlacedEvent {
      export type InputTuple = [marketId: BigNumberish, user: AddressLike, outcome: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [marketId: bigint, user: string, outcome: bigint, amount: bigint];
      export interface OutputObject {marketId: bigint, user: string, outcome: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketCreatedEvent {
      export type InputTuple = [marketId: BigNumberish, question: string, closeTime: BigNumberish, resolveTime: BigNumberish, creator: AddressLike];
      export type OutputTuple = [marketId: bigint, question: string, closeTime: bigint, resolveTime: bigint, creator: string];
      export interface OutputObject {marketId: bigint, question: string, closeTime: bigint, resolveTime: bigint, creator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketLockedEvent {
      export type InputTuple = [marketId: BigNumberish];
      export type OutputTuple = [marketId: bigint];
      export interface OutputObject {marketId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketResolvedEvent {
      export type InputTuple = [marketId: BigNumberish, outcome: BigNumberish, totalYesStake: BigNumberish, totalNoStake: BigNumberish];
      export type OutputTuple = [marketId: bigint, outcome: bigint, totalYesStake: bigint, totalNoStake: bigint];
      export interface OutputObject {marketId: bigint, outcome: bigint, totalYesStake: bigint, totalNoStake: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PayoutClaimedEvent {
      export type InputTuple = [marketId: BigNumberish, user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [marketId: bigint, user: string, amount: bigint];
      export interface OutputObject {marketId: bigint, user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PredictionMarket extends BaseContract {
    
    connect(runner?: ContractRunner | null): PredictionMarket;
    waitForDeployment(): Promise<this>;

    interface: PredictionMarketInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    claimPayout: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createMarket: TypedContractMethod<
      [question: string, closeTime: BigNumberish, resolveTime: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    getMarket: TypedContractMethod<
      [marketId: BigNumberish, ],
      [IPredictionMarket.MarketViewStructOutput],
      'view'
    >
    

    
    getUserStake: TypedContractMethod<
      [marketId: BigNumberish, user: AddressLike, ],
      [[bigint, bigint] & {yesStake: bigint, noStake: bigint }],
      'view'
    >
    

    
    lockMarket: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    placeBet: TypedContractMethod<
      [marketId: BigNumberish, outcome: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    reputationSystem: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    resolveMarket: TypedContractMethod<
      [marketId: BigNumberish, outcome: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolver: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setReputationSystem: TypedContractMethod<
      [rep: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setResolver: TypedContractMethod<
      [newResolver: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'claimPayout'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createMarket'): TypedContractMethod<
      [question: string, closeTime: BigNumberish, resolveTime: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getMarket'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [IPredictionMarket.MarketViewStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getUserStake'): TypedContractMethod<
      [marketId: BigNumberish, user: AddressLike, ],
      [[bigint, bigint] & {yesStake: bigint, noStake: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'lockMarket'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'placeBet'): TypedContractMethod<
      [marketId: BigNumberish, outcome: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'reputationSystem'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'resolveMarket'): TypedContractMethod<
      [marketId: BigNumberish, outcome: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolver'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setReputationSystem'): TypedContractMethod<
      [rep: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setResolver'): TypedContractMethod<
      [newResolver: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BetPlaced'): TypedContractEvent<BetPlacedEvent.InputTuple, BetPlacedEvent.OutputTuple, BetPlacedEvent.OutputObject>;
getEvent(key: 'MarketCreated'): TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
getEvent(key: 'MarketLocked'): TypedContractEvent<MarketLockedEvent.InputTuple, MarketLockedEvent.OutputTuple, MarketLockedEvent.OutputObject>;
getEvent(key: 'MarketResolved'): TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
getEvent(key: 'PayoutClaimed'): TypedContractEvent<PayoutClaimedEvent.InputTuple, PayoutClaimedEvent.OutputTuple, PayoutClaimedEvent.OutputObject>;

    filters: {
      
      'BetPlaced(uint256,address,uint8,uint256)': TypedContractEvent<BetPlacedEvent.InputTuple, BetPlacedEvent.OutputTuple, BetPlacedEvent.OutputObject>;
      BetPlaced: TypedContractEvent<BetPlacedEvent.InputTuple, BetPlacedEvent.OutputTuple, BetPlacedEvent.OutputObject>;
    

      'MarketCreated(uint256,string,uint256,uint256,address)': TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
      MarketCreated: TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
    

      'MarketLocked(uint256)': TypedContractEvent<MarketLockedEvent.InputTuple, MarketLockedEvent.OutputTuple, MarketLockedEvent.OutputObject>;
      MarketLocked: TypedContractEvent<MarketLockedEvent.InputTuple, MarketLockedEvent.OutputTuple, MarketLockedEvent.OutputObject>;
    

      'MarketResolved(uint256,uint8,uint256,uint256)': TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
      MarketResolved: TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
    

      'PayoutClaimed(uint256,address,uint256)': TypedContractEvent<PayoutClaimedEvent.InputTuple, PayoutClaimedEvent.OutputTuple, PayoutClaimedEvent.OutputObject>;
      PayoutClaimed: TypedContractEvent<PayoutClaimedEvent.InputTuple, PayoutClaimedEvent.OutputTuple, PayoutClaimedEvent.OutputObject>;
    
    };
  }