/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface PredictionMarketFunctionsConsumerInterface extends Interface {
    getFunction(nameOrSignature: "MAX_CALLBACK_GAS" | "creWorkflow" | "handleOracleFulfillment" | "owner" | "s_pendingMarketId" | "sendResolutionRequest" | "setOwner"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MarketResolvedFromFunctions" | "RequestFulfilled" | "RequestSent" | "ResolutionRequestSent"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_CALLBACK_GAS', values?: undefined): string;
encodeFunctionData(functionFragment: 'creWorkflow', values?: undefined): string;
encodeFunctionData(functionFragment: 'handleOracleFulfillment', values: [BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 's_pendingMarketId', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'sendResolutionRequest', values: [BigNumberish, string, string[], BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setOwner', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'MAX_CALLBACK_GAS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'creWorkflow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'handleOracleFulfillment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 's_pendingMarketId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sendResolutionRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOwner', data: BytesLike): Result;
  }

  
    export namespace MarketResolvedFromFunctionsEvent {
      export type InputTuple = [requestId: BytesLike, marketId: BigNumberish, outcome: BigNumberish];
      export type OutputTuple = [requestId: string, marketId: bigint, outcome: bigint];
      export interface OutputObject {requestId: string, marketId: bigint, outcome: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequestFulfilledEvent {
      export type InputTuple = [id: BytesLike];
      export type OutputTuple = [id: string];
      export interface OutputObject {id: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequestSentEvent {
      export type InputTuple = [id: BytesLike];
      export type OutputTuple = [id: string];
      export interface OutputObject {id: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ResolutionRequestSentEvent {
      export type InputTuple = [requestId: BytesLike, marketId: BigNumberish];
      export type OutputTuple = [requestId: string, marketId: bigint];
      export interface OutputObject {requestId: string, marketId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PredictionMarketFunctionsConsumer extends BaseContract {
    
    connect(runner?: ContractRunner | null): PredictionMarketFunctionsConsumer;
    waitForDeployment(): Promise<this>;

    interface: PredictionMarketFunctionsConsumerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_CALLBACK_GAS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    creWorkflow: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    handleOracleFulfillment: TypedContractMethod<
      [requestId: BytesLike, response: BytesLike, err: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    s_pendingMarketId: TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    sendResolutionRequest: TypedContractMethod<
      [marketId: BigNumberish, sourceCode: string, args: string[], subscriptionId: BigNumberish, donId: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    setOwner: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_CALLBACK_GAS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'creWorkflow'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'handleOracleFulfillment'): TypedContractMethod<
      [requestId: BytesLike, response: BytesLike, err: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 's_pendingMarketId'): TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'sendResolutionRequest'): TypedContractMethod<
      [marketId: BigNumberish, sourceCode: string, args: string[], subscriptionId: BigNumberish, donId: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setOwner'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'MarketResolvedFromFunctions'): TypedContractEvent<MarketResolvedFromFunctionsEvent.InputTuple, MarketResolvedFromFunctionsEvent.OutputTuple, MarketResolvedFromFunctionsEvent.OutputObject>;
getEvent(key: 'RequestFulfilled'): TypedContractEvent<RequestFulfilledEvent.InputTuple, RequestFulfilledEvent.OutputTuple, RequestFulfilledEvent.OutputObject>;
getEvent(key: 'RequestSent'): TypedContractEvent<RequestSentEvent.InputTuple, RequestSentEvent.OutputTuple, RequestSentEvent.OutputObject>;
getEvent(key: 'ResolutionRequestSent'): TypedContractEvent<ResolutionRequestSentEvent.InputTuple, ResolutionRequestSentEvent.OutputTuple, ResolutionRequestSentEvent.OutputObject>;

    filters: {
      
      'MarketResolvedFromFunctions(bytes32,uint256,uint8)': TypedContractEvent<MarketResolvedFromFunctionsEvent.InputTuple, MarketResolvedFromFunctionsEvent.OutputTuple, MarketResolvedFromFunctionsEvent.OutputObject>;
      MarketResolvedFromFunctions: TypedContractEvent<MarketResolvedFromFunctionsEvent.InputTuple, MarketResolvedFromFunctionsEvent.OutputTuple, MarketResolvedFromFunctionsEvent.OutputObject>;
    

      'RequestFulfilled(bytes32)': TypedContractEvent<RequestFulfilledEvent.InputTuple, RequestFulfilledEvent.OutputTuple, RequestFulfilledEvent.OutputObject>;
      RequestFulfilled: TypedContractEvent<RequestFulfilledEvent.InputTuple, RequestFulfilledEvent.OutputTuple, RequestFulfilledEvent.OutputObject>;
    

      'RequestSent(bytes32)': TypedContractEvent<RequestSentEvent.InputTuple, RequestSentEvent.OutputTuple, RequestSentEvent.OutputObject>;
      RequestSent: TypedContractEvent<RequestSentEvent.InputTuple, RequestSentEvent.OutputTuple, RequestSentEvent.OutputObject>;
    

      'ResolutionRequestSent(bytes32,uint256)': TypedContractEvent<ResolutionRequestSentEvent.InputTuple, ResolutionRequestSentEvent.OutputTuple, ResolutionRequestSentEvent.OutputObject>;
      ResolutionRequestSent: TypedContractEvent<ResolutionRequestSentEvent.InputTuple, ResolutionRequestSentEvent.OutputTuple, ResolutionRequestSentEvent.OutputObject>;
    
    };
  }