/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface PrivatePredictionMarketInterface extends Interface {
    getFunction(nameOrSignature: "claimPayout" | "commitBet" | "createMarket" | "getCommitmentCount" | "getMarket" | "getTotalCommitted" | "owner" | "resolveMarket" | "resolver" | "revealBet" | "setResolver"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BetCommitted" | "BetRevealed" | "MarketCreated" | "MarketResolved" | "PayoutClaimed"): EventFragment;

    encodeFunctionData(functionFragment: 'claimPayout', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'commitBet', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'createMarket', values: [string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCommitmentCount', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getMarket', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTotalCommitted', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveMarket', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolver', values?: undefined): string;
encodeFunctionData(functionFragment: 'revealBet', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setResolver', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'claimPayout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'commitBet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCommitmentCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalCommitted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveMarket', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolver', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revealBet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setResolver', data: BytesLike): Result;
  }

  
    export namespace BetCommittedEvent {
      export type InputTuple = [marketId: BigNumberish, user: AddressLike, index: BigNumberish, value: BigNumberish, commitment: BytesLike];
      export type OutputTuple = [marketId: bigint, user: string, index: bigint, value: bigint, commitment: string];
      export interface OutputObject {marketId: bigint, user: string, index: bigint, value: bigint, commitment: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BetRevealedEvent {
      export type InputTuple = [marketId: BigNumberish, user: AddressLike, outcome: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [marketId: bigint, user: string, outcome: bigint, amount: bigint];
      export interface OutputObject {marketId: bigint, user: string, outcome: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketCreatedEvent {
      export type InputTuple = [marketId: BigNumberish, question: string, closeTime: BigNumberish, resolveTime: BigNumberish, creator: AddressLike];
      export type OutputTuple = [marketId: bigint, question: string, closeTime: bigint, resolveTime: bigint, creator: string];
      export interface OutputObject {marketId: bigint, question: string, closeTime: bigint, resolveTime: bigint, creator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketResolvedEvent {
      export type InputTuple = [marketId: BigNumberish, outcome: BigNumberish, totalYesStake: BigNumberish, totalNoStake: BigNumberish];
      export type OutputTuple = [marketId: bigint, outcome: bigint, totalYesStake: bigint, totalNoStake: bigint];
      export interface OutputObject {marketId: bigint, outcome: bigint, totalYesStake: bigint, totalNoStake: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PayoutClaimedEvent {
      export type InputTuple = [marketId: BigNumberish, user: AddressLike, amount: BigNumberish];
      export type OutputTuple = [marketId: bigint, user: string, amount: bigint];
      export interface OutputObject {marketId: bigint, user: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PrivatePredictionMarket extends BaseContract {
    
    connect(runner?: ContractRunner | null): PrivatePredictionMarket;
    waitForDeployment(): Promise<this>;

    interface: PrivatePredictionMarketInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    claimPayout: TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    commitBet: TypedContractMethod<
      [marketId: BigNumberish, commitment: BytesLike, ],
      [void],
      'payable'
    >
    

    
    createMarket: TypedContractMethod<
      [question: string, closeTime: BigNumberish, resolveTime: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    getCommitmentCount: TypedContractMethod<
      [marketId: BigNumberish, user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getMarket: TypedContractMethod<
      [marketId: BigNumberish, ],
      [[bigint, string, bigint, bigint, bigint, bigint, bigint, bigint] & {id: bigint, question: string, closeTime: bigint, resolveTime: bigint, status: bigint, outcome: bigint, totalYesStake: bigint, totalNoStake: bigint }],
      'view'
    >
    

    
    getTotalCommitted: TypedContractMethod<
      [marketId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    resolveMarket: TypedContractMethod<
      [marketId: BigNumberish, rawOutcome: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolver: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    revealBet: TypedContractMethod<
      [marketId: BigNumberish, index: BigNumberish, outcome: BigNumberish, amount: BigNumberish, nonce: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setResolver: TypedContractMethod<
      [newResolver: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'claimPayout'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'commitBet'): TypedContractMethod<
      [marketId: BigNumberish, commitment: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'createMarket'): TypedContractMethod<
      [question: string, closeTime: BigNumberish, resolveTime: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCommitmentCount'): TypedContractMethod<
      [marketId: BigNumberish, user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMarket'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [[bigint, string, bigint, bigint, bigint, bigint, bigint, bigint] & {id: bigint, question: string, closeTime: bigint, resolveTime: bigint, status: bigint, outcome: bigint, totalYesStake: bigint, totalNoStake: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalCommitted'): TypedContractMethod<
      [marketId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'resolveMarket'): TypedContractMethod<
      [marketId: BigNumberish, rawOutcome: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolver'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'revealBet'): TypedContractMethod<
      [marketId: BigNumberish, index: BigNumberish, outcome: BigNumberish, amount: BigNumberish, nonce: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setResolver'): TypedContractMethod<
      [newResolver: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BetCommitted'): TypedContractEvent<BetCommittedEvent.InputTuple, BetCommittedEvent.OutputTuple, BetCommittedEvent.OutputObject>;
getEvent(key: 'BetRevealed'): TypedContractEvent<BetRevealedEvent.InputTuple, BetRevealedEvent.OutputTuple, BetRevealedEvent.OutputObject>;
getEvent(key: 'MarketCreated'): TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
getEvent(key: 'MarketResolved'): TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
getEvent(key: 'PayoutClaimed'): TypedContractEvent<PayoutClaimedEvent.InputTuple, PayoutClaimedEvent.OutputTuple, PayoutClaimedEvent.OutputObject>;

    filters: {
      
      'BetCommitted(uint256,address,uint256,uint256,bytes32)': TypedContractEvent<BetCommittedEvent.InputTuple, BetCommittedEvent.OutputTuple, BetCommittedEvent.OutputObject>;
      BetCommitted: TypedContractEvent<BetCommittedEvent.InputTuple, BetCommittedEvent.OutputTuple, BetCommittedEvent.OutputObject>;
    

      'BetRevealed(uint256,address,uint8,uint256)': TypedContractEvent<BetRevealedEvent.InputTuple, BetRevealedEvent.OutputTuple, BetRevealedEvent.OutputObject>;
      BetRevealed: TypedContractEvent<BetRevealedEvent.InputTuple, BetRevealedEvent.OutputTuple, BetRevealedEvent.OutputObject>;
    

      'MarketCreated(uint256,string,uint256,uint256,address)': TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
      MarketCreated: TypedContractEvent<MarketCreatedEvent.InputTuple, MarketCreatedEvent.OutputTuple, MarketCreatedEvent.OutputObject>;
    

      'MarketResolved(uint256,uint8,uint256,uint256)': TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
      MarketResolved: TypedContractEvent<MarketResolvedEvent.InputTuple, MarketResolvedEvent.OutputTuple, MarketResolvedEvent.OutputObject>;
    

      'PayoutClaimed(uint256,address,uint256)': TypedContractEvent<PayoutClaimedEvent.InputTuple, PayoutClaimedEvent.OutputTuple, PayoutClaimedEvent.OutputObject>;
      PayoutClaimed: TypedContractEvent<PayoutClaimedEvent.InputTuple, PayoutClaimedEvent.OutputTuple, PayoutClaimedEvent.OutputObject>;
    
    };
  }