/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPredictionMarket } from './IPredictionMarket.js';
export type { IReputationSystem } from './IReputationSystem.js';