/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IReputationSystemInterface extends Interface {
    getFunction(nameOrSignature: "getCreatorStats" | "onMarketCreated" | "onMarketResolved"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CreatorReputationUpdated" | "MarketCreatorRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'getCreatorStats', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'onMarketCreated', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'onMarketResolved', values: [BigNumberish, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'getCreatorStats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onMarketCreated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onMarketResolved', data: BytesLike): Result;
  }

  
    export namespace CreatorReputationUpdatedEvent {
      export type InputTuple = [creator: AddressLike, newScore: BigNumberish];
      export type OutputTuple = [creator: string, newScore: bigint];
      export interface OutputObject {creator: string, newScore: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MarketCreatorRegisteredEvent {
      export type InputTuple = [marketId: BigNumberish, creator: AddressLike];
      export type OutputTuple = [marketId: bigint, creator: string];
      export interface OutputObject {marketId: bigint, creator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IReputationSystem extends BaseContract {
    
    connect(runner?: ContractRunner | null): IReputationSystem;
    waitForDeployment(): Promise<this>;

    interface: IReputationSystemInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getCreatorStats: TypedContractMethod<
      [creator: AddressLike, ],
      [[bigint, bigint, bigint] & {marketsCreated: bigint, marketsResolved: bigint, reputationScore: bigint }],
      'view'
    >
    

    
    onMarketCreated: TypedContractMethod<
      [marketId: BigNumberish, creator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    onMarketResolved: TypedContractMethod<
      [marketId: BigNumberish, creator: AddressLike, outcome: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getCreatorStats'): TypedContractMethod<
      [creator: AddressLike, ],
      [[bigint, bigint, bigint] & {marketsCreated: bigint, marketsResolved: bigint, reputationScore: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'onMarketCreated'): TypedContractMethod<
      [marketId: BigNumberish, creator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'onMarketResolved'): TypedContractMethod<
      [marketId: BigNumberish, creator: AddressLike, outcome: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CreatorReputationUpdated'): TypedContractEvent<CreatorReputationUpdatedEvent.InputTuple, CreatorReputationUpdatedEvent.OutputTuple, CreatorReputationUpdatedEvent.OutputObject>;
getEvent(key: 'MarketCreatorRegistered'): TypedContractEvent<MarketCreatorRegisteredEvent.InputTuple, MarketCreatorRegisteredEvent.OutputTuple, MarketCreatorRegisteredEvent.OutputObject>;

    filters: {
      
      'CreatorReputationUpdated(address,uint256)': TypedContractEvent<CreatorReputationUpdatedEvent.InputTuple, CreatorReputationUpdatedEvent.OutputTuple, CreatorReputationUpdatedEvent.OutputObject>;
      CreatorReputationUpdated: TypedContractEvent<CreatorReputationUpdatedEvent.InputTuple, CreatorReputationUpdatedEvent.OutputTuple, CreatorReputationUpdatedEvent.OutputObject>;
    

      'MarketCreatorRegistered(uint256,address)': TypedContractEvent<MarketCreatorRegisteredEvent.InputTuple, MarketCreatorRegisteredEvent.OutputTuple, MarketCreatorRegisteredEvent.OutputObject>;
      MarketCreatorRegistered: TypedContractEvent<MarketCreatorRegisteredEvent.InputTuple, MarketCreatorRegisteredEvent.OutputTuple, MarketCreatorRegisteredEvent.OutputObject>;
    
    };
  }